baseURL = "https://blog.florianschroedl.com/"
languageCode = "en-us"
title = "Personal Blog"
theme = "hyde"

[params]
  description = "Personal Blog"
  author = "Florian Schrödl"

[taxonomies]
  tag = "tags"

[author]
  name = "Florian Schrödl"
  email = "hello@florianschroedl.com"
